### PR TITLE
Use NPM_TOKEN to access private modules

### PR DESCRIPTION
**Pull request by flintinatux**
insert token

See [the docs](https://docs.npmjs.com/private-modules/ci-server-config) for details.  I've tested this locally with a :magic: branch of `rise-runtime`.

### CODE REVIEW

**Comment by tecnobrat** [comment]
I assume you're gonna edit the `docker-compose.yml` (or override) to have something like:

```
build:
  context: .
  args:
    NPM_TOKEN: ${NPM_TOKEN}
```

And then require people to have `NPM_TOKEN` set in their local shell?

**Comment by flintinatux** [comment]
@tecnobrat: That's the plan.  I really wanted to avoid putting a `.npmrc` in every project.  The default `ARG NPM_TOKEN=secret` should allow it to install public modules without an actual token.

However, my concern with this plan is that the `ARG` instruction is only valid for the _current_ `Dockerfile` (in this case, the parent).  So I wasn't able to remove that line from `rise-runtime/Dockerfile`.  Which means _every_ project would need an `ARG` line or you get this error:

```
Error: Failed to replace env in config: ${NPM_TOKEN}
```

So I'm wondering if I just put the `.npmrc` in each service project as needed and forget about it.

**Comment by flintinatux** [comment]
Closing because `ARG` and `ENV` and UUGGGGHHHHH

**Comment by pklingem** [comment]
`AAARRRRGGGGGG`

**Pull request closed without merging**
